name: github action demo

on: 
  push:
    branches:
    - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run:
        gcloud auth configure-docker europe-west4-docker.pkg.dev
        docker build -t europe-west4-docker.pkg.dev/my-react-project-97ea7/docker-cloud/node-docker-app
        docker push europe-west4-docker.pkg.dev/my-react-project-97ea7/docker-cloud/node-docker-app