name: github action test

on: 
  push:
    branches:
    - 'master'

permissions:
  contents: read
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: Java Check
      run: java --version